import "../globals.css";

export const metadata = {
  title: "LEAD",
  description: "Generated by create next app",
};

export default function RegistrationLayout({ children }) {
  return children;
}
